# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'VLCTestObjectiveC' do
    
    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for VLCTestObjectiveC
    pod 'MobileVLCKit', '~>3.3.0'

end
