# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SQLCipher_v1' do

    # Comment the next line if you don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for SQLCipher_v1
    pod 'SQLCipher', '~>4.0'
    
end
