A_DIR_ROOT = $$(A_DIR_USING_JAVA)

A_DIR_MODULES = $$A_DIR_ROOT/Modules

A_DIR_MODULE1 = $$A_DIR_MODULES/Module1
A_PRI_MODULE1 = $$A_DIR_MODULE1/Module1.pri

A_DIR_MODULE2 = $$A_DIR_MODULES/Module2
A_PRI_MODULE2 = $$A_DIR_MODULE2/Module2.pri
