# --------------------------
# Module properties

set(A_MODULE_LANGUAGES CXX)
set(A_MODULE_QT_COMPONENTS Core)

set(A_TARGET_INCLUDE_DIRECTORIES_PRIVATE
	${A_TARGET_INCLUDE_DIRECTORIES_PRIVATE}
	${A_DIR_APPLICATION_MODULE_LOGGER}
)


# --------------------------
# Module sources

set(A_SOURCES_CPP_HEADERS
	${A_SOURCES_CPP_HEADERS}
	${A_DIR_APPLICATION_MODULE_LOGGER}/alogger.h
	${A_DIR_APPLICATION_MODULE_LOGGER}/aloggerdatamodels.h
	${A_DIR_APPLICATION_MODULE_LOGGER}/aloggerglobal.h
)

set(A_SOURCES_CPP
	${A_SOURCES_CPP}
	${A_DIR_APPLICATION_MODULE_LOGGER}/alogger.cpp
)

set(A_SOURCES_PRECOMPILED_HEADERS_PUBLIC
	${A_SOURCES_PRECOMPILED_HEADERS_PUBLIC}
	${A_DIR_APPLICATION_MODULE_LOGGER}/aloggerpch.h
)


# --------------------------
# Define project

A_SetLanguages(${A_MODULE_LANGUAGES})
A_SetQtComponents(${A_MODULE_QT_COMPONENTS})

