#!/usr/bin/perl

use strict;
use warnings FATAL => 'all';
use feature qw/say/;

use Rex -feature => [ '1.4' ];

BEGIN {

	use Cwd qw();
	push(@INC,Cwd::cwd());
	push(@INC,Cwd::cwd()."/ALogger");
	push(@INC,Cwd::cwd()."/ATime");
};

use ATime::Timestamp;
use ALogger::Handler;

our $oLogger = ALogger::Handler->mGetInstance();
$oLogger->mSetRexConfigAutoDie(1);
$oLogger->mSetRexLoggerDebug(1);
$oLogger->mSetRexLoggerFormat("%h %s");

# say(ATime::Timestamp::mSeconds());
# say(ATime::Timestamp::mMilliseconds());
# say(ATime::Timestamp::mMicroseconds());

$oLogger->mDebug("Debug message");
$oLogger->mInfo("Info message");
$oLogger->mUser("User message");

1;