# ---------------------------------
# Global variables

set(A_TARGET_LANGUAGES)
set(A_TARGET_LINK_LIBRARIES_PUBLIC)
set(A_TARGET_LINK_LIBRARIES_PRIVATE)
set(A_TARGET_COMPILE_DEFINITIONS_PUBLIC)
set(A_TARGET_COMPILE_DEFINITIONS_PRIVATE)
set(A_TARGET_INCLUDE_DIRECTORIES_PUBLIC)
set(A_TARGET_INCLUDE_DIRECTORIES_PRIVATE)
set(A_TARGET_QT_MODULES)

set(A_SOURCES)
set(A_SOURCES_RESOURCES)
set(A_SOURCES_CPP_HEADERS)
set(A_SOURCES_CPP)
set(A_SOURCES_C_HEADERS)
set(A_SOURCES_C)
set(A_SOURCES_PRECOMPILED_HEADERS_PUBLIC)
set(A_SOURCES_PRECOMPILED_HEADERS_PRIVATE)

if(IOS)

	set(A_SOURCES_SWIFT_OBJC_INTERFACE_HEADER_NAME)
	set(A_SOURCES_SWIFT_OBJC_BRIDGING_HEADER)

	set(A_SOURCES_OBJECTIVE_HEADERS)
	set(A_SOURCES_OBJECTIVE_CPP)
	set(A_SOURCES_SWIFT)

endif()

if(ANDROID)

endif()
